language: generic
sudo: required
sevices: 
  - docker

before-install:
  - docker build -t aninda08/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aninda08/react-test npm run test

after_success:
  - docker build -t aninda08/multi-client ./client
  - docker build -t aninda08/multi-nginx ./nginx
  - docker build -t aninda08/multi-server ./server
  - docker build -t aninda08/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aninda08/multi-client
  - docker push aninda08/multi-nginx
  - docker push aninda08/multi-server
  - docker push aninda08/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-667083208095'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY